// <auto-generated />
using System;
using GardenCompanion.Api.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GardenCompanion.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260414164615_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("GardenCompanion.Api.Domain.Entities.AmendmentLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AmendmentType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("AppliedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GardenBedId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PlantingId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(10,3)");

                    b.Property<string>("QuantityUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppliedAt")
                        .HasDatabaseName("IX_AmendmentLogs_AppliedAt");

                    b.HasIndex("GardenBedId")
                        .HasDatabaseName("IX_AmendmentLogs_GardenBedId");

                    b.HasIndex("PlantingId");

                    b.ToTable("AmendmentLogs", (string)null);
                });

            modelBuilder.Entity("GardenCompanion.Api.Domain.Entities.Garden", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId")
                        .HasDatabaseName("IX_Gardens_HouseholdId");

                    b.ToTable("Gardens", (string)null);
                });

            modelBuilder.Entity("GardenCompanion.Api.Domain.Entities.GardenBed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("DepthInches")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal?>("DiameterFeet")
                        .HasColumnType("decimal(6,2)");

                    b.Property<Guid>("GardenId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("LengthFeet")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Shape")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SoilType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SunExposure")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("VolumeGallons")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal?>("WidthFeet")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("GardenId")
                        .HasDatabaseName("IX_GardenBeds_GardenId");

                    b.ToTable("GardenBeds", (string)null);
                });

            modelBuilder.Entity("GardenCompanion.Api.Domain.Entities.GardenMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GardenId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("InvitedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InvitedByUserId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_GardenMembers_UserId");

                    b.HasIndex("GardenId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("UQ_GardenMembers_GardenUser");

                    b.ToTable("GardenMembers", (string)null);
                });

            modelBuilder.Entity("GardenCompanion.Api.Domain.Entities.GardenTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GardenBedId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GardenId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PlantingId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("CompletedAt")
                        .HasDatabaseName("IX_GardenTasks_CompletedAt");

                    b.HasIndex("DueDate")
                        .HasDatabaseName("IX_GardenTasks_DueDate");

                    b.HasIndex("GardenBedId");

                    b.HasIndex("GardenId")
                        .HasDatabaseName("IX_GardenTasks_GardenId");

                    b.HasIndex("PlantingId");

                    b.ToTable("GardenTasks", (string)null);
                });

            modelBuilder.Entity("GardenCompanion.Api.Domain.Entities.GardenType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_GardenTypes_Name");

                    b.ToTable("GardenTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Vegetable"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Fruit"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Herb"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Flower"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Orchard"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Greenhouse"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("GardenCompanion.Api.Domain.Entities.HarvestLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("HarvestDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HarvestedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlantingId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(10,3)");

                    b.Property<string>("QuantityUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HarvestDate")
                        .HasDatabaseName("IX_HarvestLogs_HarvestDate");

                    b.HasIndex("HarvestedByUserId")
                        .HasDatabaseName("IX_HarvestLogs_HarvestedByUserId");

                    b.HasIndex("PlantingId")
                        .HasDatabaseName("IX_HarvestLogs_PlantingId");

                    b.ToTable("HarvestLogs", (string)null);
                });

            modelBuilder.Entity("GardenCompanion.Api.Domain.Entities.Household", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("WeatherStationIntegrationId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnedByUserId")
                        .HasDatabaseName("IX_Households_OwnedByUserId");

                    b.HasIndex("WeatherStationIntegrationId")
                        .IsUnique();

                    b.ToTable("Households", (string)null);
                });

            modelBuilder.Entity("GardenCompanion.Api.Domain.Entities.HouseholdMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_HouseholdMembers_UserId");

                    b.HasIndex("HouseholdId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("UQ_HouseholdMembers_HouseholdUser");

                    b.ToTable("HouseholdMembers", (string)null);
                });

            modelBuilder.Entity("GardenCompanion.Api.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_PasswordResetTokens_ExpiresAt");

                    b.HasIndex("Token")
                        .HasDatabaseName("IX_PasswordResetTokens_Token");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens", (string)null);
                });

            modelBuilder.Entity("GardenCompanion.Api.Domain.Entities.PestDiseaseLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GardenBedId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ObservedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PlantingId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("TreatmentApplied")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GardenBedId")
                        .HasDatabaseName("IX_PestDiseaseLogs_GardenBedId");

                    b.HasIndex("PlantingId")
                        .HasDatabaseName("IX_PestDiseaseLogs_PlantingId");

                    b.HasIndex("ResolvedAt")
                        .HasDatabaseName("IX_PestDiseaseLogs_ResolvedAt");

                    b.ToTable("PestDiseaseLogs", (string)null);
                });

            modelBuilder.Entity("GardenCompanion.Api.Domain.Entities.Plant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CachedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommonName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ContributedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DaysToMaturity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalSource")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Family")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsGlobal")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("MinDepthInches")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal?>("MinSpacingInches")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("ScientificName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SunRequirement")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("WaterRequirement")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CommonName")
                        .HasDatabaseName("IX_Plants_CommonName");

                    b.HasIndex("ContributedByUserId");

                    b.HasIndex("ExternalSource")
                        .HasDatabaseName("IX_Plants_ExternalSource");

                    b.HasIndex("Family")
                        .HasDatabaseName("IX_Plants_Family");

                    b.HasIndex("IsGlobal", "IsApproved")
                        .HasDatabaseName("IX_Plants_IsGlobal");

                    b.ToTable("Plants", (string)null);
                });

            modelBuilder.Entity("GardenCompanion.Api.Domain.Entities.PlantCompanion", b =>
                {
                    b.Property<Guid>("PlantId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanionPlantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelationshipType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("PlantId", "CompanionPlantId");

                    b.HasIndex("CompanionPlantId");

                    b.ToTable("PlantCompanions", (string)null);
                });

            modelBuilder.Entity("GardenCompanion.Api.Domain.Entities.Planting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ActualEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ExpectedHarvestDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GardenBedId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PlantId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("PlantedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlantingType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeasonType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("SeasonYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GardenBedId")
                        .HasDatabaseName("IX_Plantings_GardenBedId");

                    b.HasIndex("PlantId")
                        .HasDatabaseName("IX_Plantings_PlantId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Plantings_Status");

                    b.HasIndex("SeasonYear", "SeasonType")
                        .HasDatabaseName("IX_Plantings_Season");

                    b.ToTable("Plantings", (string)null);
                });

            modelBuilder.Entity("GardenCompanion.Api.Domain.Entities.PlantingObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ObservationType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ObservedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlantingId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ObservedAt")
                        .HasDatabaseName("IX_PlantingObservations_ObservedAt");

                    b.HasIndex("PlantingId")
                        .HasDatabaseName("IX_PlantingObservations_PlantingId");

                    b.ToTable("PlantingObservations", (string)null);
                });

            modelBuilder.Entity("GardenCompanion.Api.Domain.Entities.SoilTest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GardenBedId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NitrogenPpm")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OrganicMatterPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("PhLevel")
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal?>("PhosphorusPpm")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal?>("PotassiumPpm")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("TestSource")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("TestedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GardenBedId")
                        .HasDatabaseName("IX_SoilTests_GardenBedId");

                    b.HasIndex("TestedAt")
                        .HasDatabaseName("IX_SoilTests_TestedAt");

                    b.ToTable("SoilTests", (string)null);
                });

            modelBuilder.Entity("GardenCompanion.Api.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("GardenCompanion.Api.Domain.Entities.UserInsight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GardenBedId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GardenId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("TEXT");

                    b.Property<string>("InsightType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_UserInsights_ExpiresAt");

                    b.HasIndex("GardenBedId");

                    b.HasIndex("GardenId");

                    b.HasIndex("HouseholdId", "IsRead", "GeneratedAt")
                        .HasDatabaseName("IX_UserInsights_HouseholdId");

                    b.ToTable("UserInsights", (string)null);
                });

            modelBuilder.Entity("GardenCompanion.Api.Domain.Entities.UserRefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .HasDatabaseName("IX_UserRefreshTokens_Token");

                    b.HasIndex("UserId", "RevokedAt")
                        .HasDatabaseName("IX_UserRefreshTokens_UserId_Active");

                    b.ToTable("UserRefreshTokens", (string)null);
                });

            modelBuilder.Entity("GardenCompanion.Api.Domain.Entities.UserSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("AverageFrostDateFall")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("AverageFrostDateSpring")
                        .HasColumnType("TEXT");

                    b.Property<string>("LengthUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("LocationLatitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("LocationLongitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ShareHarvestData")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SharePlantingData")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShareWeatherData")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TemperatureUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("UsdaHardinessZone")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("VolumeUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("WeightUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("UQ_UserSettings_UserId");

                    b.ToTable("UserSettings", (string)null);
                });

            modelBuilder.Entity("GardenCompanion.Api.Domain.Entities.WeatherObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("DewPointF")
                        .HasColumnType("decimal(6,2)");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Humidity")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("ObservedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecipitationRateInPerHr")
                        .HasColumnType("decimal(6,3)");

                    b.Property<decimal>("PrecipitationTotalIn")
                        .HasColumnType("decimal(6,3)");

                    b.Property<decimal?>("PressureInHg")
                        .HasColumnType("decimal(6,3)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("StationId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TemperatureF")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal?>("UvIndex")
                        .HasColumnType("decimal(4,1)");

                    b.Property<int?>("WindDirectionDegrees")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("WindSpeedMph")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("ObservedAt")
                        .HasDatabaseName("IX_WeatherObservations_ObservedAt");

                    b.HasIndex("HouseholdId", "ObservedAt")
                        .HasDatabaseName("IX_WeatherObservations_HouseholdId_ObservedAt");

                    b.ToTable("WeatherObservations", (string)null);
                });

            modelBuilder.Entity("GardenCompanion.Api.Domain.Entities.WeatherStationIntegration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKey")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("StationId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId")
                        .IsUnique()
                        .HasDatabaseName("UQ_WeatherStationIntegrations_HouseholdId");

                    b.ToTable("WeatherStationIntegrations", (string)null);
                });

            modelBuilder.Entity("GardenGardenType", b =>
                {
                    b.Property<int>("GardenTypesId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("GardensId")
                        .HasColumnType("TEXT");

                    b.HasKey("GardenTypesId", "GardensId");

                    b.HasIndex("GardensId");

                    b.ToTable("GardenGardenTypes", (string)null);
                });

            modelBuilder.Entity("GardenCompanion.Api.Domain.Entities.AmendmentLog", b =>
                {
                    b.HasOne("GardenCompanion.Api.Domain.Entities.GardenBed", "GardenBed")
                        .WithMany("AmendmentLogs")
                        .HasForeignKey("GardenBedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GardenCompanion.Api.Domain.Entities.Planting", "Planting")
                        .WithMany("AmendmentLogs")
                        .HasForeignKey("PlantingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("GardenBed");

                    b.Navigation("Planting");
                });

            modelBuilder.Entity("GardenCompanion.Api.Domain.Entities.Garden", b =>
                {
                    b.HasOne("GardenCompanion.Api.Domain.Entities.Household", "Household")
                        .WithMany("Gardens")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("GardenCompanion.Api.Domain.Entities.GardenBed", b =>
                {
                    b.HasOne("GardenCompanion.Api.Domain.Entities.Garden", "Garden")
                        .WithMany("Beds")
                        .HasForeignKey("GardenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Garden");
                });

            modelBuilder.Entity("GardenCompanion.Api.Domain.Entities.GardenMember", b =>
                {
                    b.HasOne("GardenCompanion.Api.Domain.Entities.Garden", "Garden")
                        .WithMany("Members")
                        .HasForeignKey("GardenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GardenCompanion.Api.Domain.Entities.User", "InvitedBy")
                        .WithMany()
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GardenCompanion.Api.Domain.Entities.User", "User")
                        .WithMany("GardenMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Garden");

                    b.Navigation("InvitedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GardenCompanion.Api.Domain.Entities.GardenTask", b =>
                {
                    b.HasOne("GardenCompanion.Api.Domain.Entities.User", "AssignedTo")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GardenCompanion.Api.Domain.Entities.GardenBed", "GardenBed")
                        .WithMany("Tasks")
                        .HasForeignKey("GardenBedId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GardenCompanion.Api.Domain.Entities.Garden", "Garden")
                        .WithMany("Tasks")
                        .HasForeignKey("GardenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GardenCompanion.Api.Domain.Entities.Planting", "Planting")
                        .WithMany("Tasks")
                        .HasForeignKey("PlantingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedTo");

                    b.Navigation("Garden");

                    b.Navigation("GardenBed");

                    b.Navigation("Planting");
                });

            modelBuilder.Entity("GardenCompanion.Api.Domain.Entities.HarvestLog", b =>
                {
                    b.HasOne("GardenCompanion.Api.Domain.Entities.User", "HarvestedBy")
                        .WithMany("HarvestLogs")
                        .HasForeignKey("HarvestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GardenCompanion.Api.Domain.Entities.Planting", "Planting")
                        .WithMany("HarvestLogs")
                        .HasForeignKey("PlantingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HarvestedBy");

                    b.Navigation("Planting");
                });

            modelBuilder.Entity("GardenCompanion.Api.Domain.Entities.Household", b =>
                {
                    b.HasOne("GardenCompanion.Api.Domain.Entities.User", "Owner")
                        .WithMany("OwnedHouseholds")
                        .HasForeignKey("OwnedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GardenCompanion.Api.Domain.Entities.WeatherStationIntegration", "WeatherStationIntegration")
                        .WithOne()
                        .HasForeignKey("GardenCompanion.Api.Domain.Entities.Household", "WeatherStationIntegrationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Owner");

                    b.Navigation("WeatherStationIntegration");
                });

            modelBuilder.Entity("GardenCompanion.Api.Domain.Entities.HouseholdMember", b =>
                {
                    b.HasOne("GardenCompanion.Api.Domain.Entities.Household", "Household")
                        .WithMany("Members")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GardenCompanion.Api.Domain.Entities.User", "User")
                        .WithMany("HouseholdMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Household");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GardenCompanion.Api.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("GardenCompanion.Api.Domain.Entities.User", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GardenCompanion.Api.Domain.Entities.PestDiseaseLog", b =>
                {
                    b.HasOne("GardenCompanion.Api.Domain.Entities.GardenBed", "GardenBed")
                        .WithMany("PestDiseaseLogs")
                        .HasForeignKey("GardenBedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GardenCompanion.Api.Domain.Entities.Planting", "Planting")
                        .WithMany("PestDiseaseLogs")
                        .HasForeignKey("PlantingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("GardenBed");

                    b.Navigation("Planting");
                });

            modelBuilder.Entity("GardenCompanion.Api.Domain.Entities.Plant", b =>
                {
                    b.HasOne("GardenCompanion.Api.Domain.Entities.User", "ContributedBy")
                        .WithMany()
                        .HasForeignKey("ContributedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ContributedBy");
                });

            modelBuilder.Entity("GardenCompanion.Api.Domain.Entities.PlantCompanion", b =>
                {
                    b.HasOne("GardenCompanion.Api.Domain.Entities.Plant", "CompanionPlant")
                        .WithMany()
                        .HasForeignKey("CompanionPlantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GardenCompanion.Api.Domain.Entities.Plant", "Plant")
                        .WithMany("CompanionRelationships")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanionPlant");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("GardenCompanion.Api.Domain.Entities.Planting", b =>
                {
                    b.HasOne("GardenCompanion.Api.Domain.Entities.GardenBed", "GardenBed")
                        .WithMany("Plantings")
                        .HasForeignKey("GardenBedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GardenCompanion.Api.Domain.Entities.Plant", "Plant")
                        .WithMany("Plantings")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GardenBed");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("GardenCompanion.Api.Domain.Entities.PlantingObservation", b =>
                {
                    b.HasOne("GardenCompanion.Api.Domain.Entities.Planting", "Planting")
                        .WithMany("Observations")
                        .HasForeignKey("PlantingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Planting");
                });

            modelBuilder.Entity("GardenCompanion.Api.Domain.Entities.SoilTest", b =>
                {
                    b.HasOne("GardenCompanion.Api.Domain.Entities.GardenBed", "GardenBed")
                        .WithMany("SoilTests")
                        .HasForeignKey("GardenBedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GardenBed");
                });

            modelBuilder.Entity("GardenCompanion.Api.Domain.Entities.UserInsight", b =>
                {
                    b.HasOne("GardenCompanion.Api.Domain.Entities.GardenBed", "GardenBed")
                        .WithMany("Insights")
                        .HasForeignKey("GardenBedId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GardenCompanion.Api.Domain.Entities.Garden", "Garden")
                        .WithMany("Insights")
                        .HasForeignKey("GardenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GardenCompanion.Api.Domain.Entities.Household", "Household")
                        .WithMany("Insights")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Garden");

                    b.Navigation("GardenBed");

                    b.Navigation("Household");
                });

            modelBuilder.Entity("GardenCompanion.Api.Domain.Entities.UserRefreshToken", b =>
                {
                    b.HasOne("GardenCompanion.Api.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GardenCompanion.Api.Domain.Entities.UserSettings", b =>
                {
                    b.HasOne("GardenCompanion.Api.Domain.Entities.User", "User")
                        .WithOne("Settings")
                        .HasForeignKey("GardenCompanion.Api.Domain.Entities.UserSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GardenCompanion.Api.Domain.Entities.WeatherObservation", b =>
                {
                    b.HasOne("GardenCompanion.Api.Domain.Entities.Household", "Household")
                        .WithMany("WeatherObservations")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("GardenCompanion.Api.Domain.Entities.WeatherStationIntegration", b =>
                {
                    b.HasOne("GardenCompanion.Api.Domain.Entities.Household", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("GardenGardenType", b =>
                {
                    b.HasOne("GardenCompanion.Api.Domain.Entities.GardenType", null)
                        .WithMany()
                        .HasForeignKey("GardenTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GardenCompanion.Api.Domain.Entities.Garden", null)
                        .WithMany()
                        .HasForeignKey("GardensId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GardenCompanion.Api.Domain.Entities.Garden", b =>
                {
                    b.Navigation("Beds");

                    b.Navigation("Insights");

                    b.Navigation("Members");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("GardenCompanion.Api.Domain.Entities.GardenBed", b =>
                {
                    b.Navigation("AmendmentLogs");

                    b.Navigation("Insights");

                    b.Navigation("PestDiseaseLogs");

                    b.Navigation("Plantings");

                    b.Navigation("SoilTests");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("GardenCompanion.Api.Domain.Entities.Household", b =>
                {
                    b.Navigation("Gardens");

                    b.Navigation("Insights");

                    b.Navigation("Members");

                    b.Navigation("WeatherObservations");
                });

            modelBuilder.Entity("GardenCompanion.Api.Domain.Entities.Plant", b =>
                {
                    b.Navigation("CompanionRelationships");

                    b.Navigation("Plantings");
                });

            modelBuilder.Entity("GardenCompanion.Api.Domain.Entities.Planting", b =>
                {
                    b.Navigation("AmendmentLogs");

                    b.Navigation("HarvestLogs");

                    b.Navigation("Observations");

                    b.Navigation("PestDiseaseLogs");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("GardenCompanion.Api.Domain.Entities.User", b =>
                {
                    b.Navigation("GardenMemberships");

                    b.Navigation("HarvestLogs");

                    b.Navigation("HouseholdMemberships");

                    b.Navigation("OwnedHouseholds");

                    b.Navigation("PasswordResetTokens");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Settings");
                });
#pragma warning restore 612, 618
        }
    }
}
